### ISSUE TITLE
How much time it takes to train on the gpu

### ISSUE THREAD

**Issue by hannanyi** [taoxugit/AttnGAN#106]
I wonder how long it takes to train 600 rounds on a 3060, 12G gpu?  Have any of you run training, can provide a reference？

**Comment by kyunghoyu** [comment]
my gpu is a5000 * 4.
so i change this repo code to run multi gpu.
but, RNN model chagne fail...
just i warp cnn, generator, discriminator, torch.nn.dataparallel()

i setup 8batch, total batch 10478,1 step maybe 1 minute,
total time 174hours

**Comment by hannanyi** [comment]
> my gpu is a5000 * 4. so i change this repo code to run multi gpu. but, RNN model chagne fail... just i warp cnn, generator, discriminator, torch.nn.dataparallel()
> 
> i setup 8batch, total batch 10478,1 step maybe 1 minute, total time 174hours
Similarly, I can only set batchsize to 8 on 3060, and it takes about 30 minutes to run an epoch

**Comment by kyunghoyu** [comment]
> 

what dataset tranning? i use MSCOCO

**Comment by hannanyi** [comment]
> > 
> 
> what dataset tranning? i use MSCOCO

I tested it with the CUB data set first
