### ISSUE TITLE
External dataset

### ISSUE THREAD

**Issue by ZhukIvan** [taoxugit/AttnGAN#4]
Hey. First of all need to say that job and result is absolutely amazing. Thank you for your work and sharing the code with the community.

Going through the steps to run your code with your data is quite easy and I get the same result as yours. But when i try to figure out how to test your architecture on external data i faced the issue of preprocessed metadata for each dataset you work with.

So can you please list some steps on how to feed some external data (aka bunch of images with captions) to your model (including pretraining DAMSM and embedding vectors). Suppose this is will be very useful information to expand your research on broad spheres.

**Comment by RaiAbhishek** [comment]
hello @ZhukIvan , i see you closed the issue, did you get your issue resolved? in that case, can you please guide me a little on that?

**Comment by RaiAbhishek** [comment]
hello @ZhukIvan, i see you closed the issue, did you get it resolved? in that case, can you please guide me a little on that?

**Comment by balag59** [comment]
> Hey @RaiAbhishek ! Yes I've solved this problem. Basically, the code is fine all you need to do is to pay close attention on folder structure of 2 existing examples (birds and coco). The difference is birds dataset have a classes and coco is not. So depending of your data you just mimic relative folder structure and write you config files ... may be fix some bugs on the road )
> Good luck

Hi @ZhukIvan ,
This helps a lot thanks! If I need to train with my own dataset then I will need to train my own DAMSM encoder right? More importantly, what do I do about the preprocessed metadata for my own dataset? It's not related to the existing datasets in any way. How do I obtain the captions.pickle and filenames.pickle for my own dataset?
Thanks!
